### ISSUE TITLE
KeyError: 'consumer_key'

### ISSUE THREAD

**Issue by shgdym** [miguelmalvarez/downloadTwitterPictures#10]
D:\My Documents\Downloads\Compressed\downloadTwitterPictures-master>python run.py --username NASA --num 10 --replies --retweets --config config.cfg --output ../NASA_Pic
tures
Traceback (most recent call last):
  File "D:\My Documents\Downloads\Compressed\downloadTwitterPictures-master\run.py", line 123, in <module>
    main()
  File "D:\My Documents\Downloads\Compressed\downloadTwitterPictures-master\run.py", line 113, in main
    auth = authorise_twitter_api(config)
  File "D:\My Documents\Downloads\Compressed\downloadTwitterPictures-master\run.py", line 48, in authorise_twitter_api
    auth = OAuthHandler(config['DEFAULT']['consumer_key'], config['DEFAULT']['consumer_secret'])
  File "C:\Users\Administrator.PC-202011301334\AppData\Local\Programs\Python\Python39\lib\configparser.py", line 1254, in __getitem__
    raise KeyError(key)
KeyError: 'consumer_key'

**Comment by miguelmalvarez** [comment]
Hi, can you confirm that you have a 'config.cfg' file where you have added your own consumer_key for the twitter API?

My (old) blogpost related to this codebase explains how to do this: https://miguelmalvarez.com/2015/03/03/download-the-pictures-from-a-twitter-feed-using-python/

**Comment by shgdym** [comment]
thank you

**Comment by imnimesh** [comment]
Hi, i am getting the same error, can you pleas ehelp me out.

Traceback (most recent call last):
  File "run.py", line 123, in <module>
    main()
  File "run.py", line 113, in main
    auth = authorise_twitter_api(config)
  File "run.py", line 48, in authorise_twitter_api
    auth = OAuthHandler(config['DEFAULT']['consumer_key'], config['DEFAULT']['consumer_secret'])
  File "/usr/lib/python3.7/configparser.py", line 1251, in __getitem__
    raise KeyError(key)
KeyError: 'consumer_key'



my cofig.cfg file 

[DEFAULT]
consumer_key = "AxOyrvszMC6FiQVijO"
consumer_secret = "68LVeWzJJPgiTgi2oKMEk"
access_token = "12927919298104tLZXZ1sMXXYT"
access_secret = "n0cOgdGm1LWS6ZwXHNdKrqLgP0S"
