### ISSUE TITLE
Twitter Error Response: status code = 400

### ISSUE THREAD

**Issue by ffffff-Fox** [miguelmalvarez/downloadTwitterPictures#11]
linky@DESKTOP-9PNPQDL: /Python/Scraper/downloadTwitterPictures$ python3 run.py --username NatGeoPhotos --num 5
Traceback (most recent call last):
  File "run.py", line 123, in <module>
    main()
  File "run.py", line 119, in main
    download_images_by_user(api, username, retweets, replies, num_tweets, output_folder)
  File "run.py", line 93, in download_images_by_user
    download_images(status, num_tweets, output_folder)
  File "run.py", line 73, in download_images
    for tweet_status in status:
  File "/home/linky/.local/lib/python3.8/site-packages/tweepy/cursor.py", line 51, in next
    return self.next()
  File "/home/linky/.local/lib/python3.8/site-packages/tweepy/cursor.py", line 243, in next
    self.current_page = self.page_iterator.next()
  File "/home/linky/.local/lib/python3.8/site-packages/tweepy/cursor.py", line 132, in next
    data = self.method(max_id=self.max_id, parser=RawParser(), *self.args, **self.kwargs)
  File "/home/linky/.local/lib/python3.8/site-packages/tweepy/binder.py", line 253, in _call
    return method.execute()
  File "/home/linky/.local/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: Twitter error response: status code = 400
linky@DESKTOP-9PNPQDL:~/Python/Scraper/downloadTwitterPictures$

**Comment by imnimesh** [comment]
hi, can you tell me how you get rid of this error.

Thanks
